### ISSUE TITLE
Viewing sets

### ISSUE THREAD

**Issue by MohammadShabib** [aerospike/aerospike-jdbc#16]
when trying to view a table (by double-clicking on the table ) the query is wrong

the expected query should be
```
SELECT *
FROM dsclocal.Counter
```

but the actual query 
```
SELECT t.*
FROM Counter t
```
![image](https://user-images.githubusercontent.com/72793336/196009227-ad8d980b-a1de-400f-a2fc-ca57a7c917c4.png)

I'm using Aerospike JDBC Driver 1.7.0

**Comment by reugn** [comment]
I believe this is what the client tool generates for you. Which one are you using?

**Comment by MohammadShabib** [comment]
I'm using JetBrains DataGrip

**Comment by MohammadShabib** [comment]
but I also installed DBeaver, same issue 
but the query is different, it doesn't add the NAMESPACE name.
`SELECT *
FROM Counter`

**Comment by reugn** [comment]
Could you share a screenshot of the screen after you double-click on a table name using DBeaver?

**Comment by MohammadShabib** [comment]
It execute this and causes an error 
![image](https://user-images.githubusercontent.com/72793336/196749149-c67d156a-2027-4e10-a29c-9a36c0f66e16.png)

**here is the log**

!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2022-10-19 19:23:26.865
!MESSAGE Internal jdbc driver error
!STACK 0
java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:294)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:331)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:186)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4949)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.aerospike.client.AerospikeException$InvalidNamespace: Error 20,1: Namespace not found in partition map: null
	at com.aerospike.client.query.PartitionTracker.assignPartitionsToNodes(PartitionTracker.java:194)
	at com.aerospike.client.command.ScanExecutor.scanPartitions(ScanExecutor.java:44)
	at com.aerospike.client.AerospikeClient.scanAll(AerospikeClient.java:2157)
	at com.aerospike.jdbc.schema.AerospikeSchemaBuilder.lambda$getSchema$4(AerospikeSchemaBuilder.java:48)
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at com.aerospike.jdbc.schema.AerospikeSchemaBuilder.getSchema(AerospikeSchemaBuilder.java:37)
	at com.aerospike.jdbc.query.SelectQueryHandler.execute(SelectQueryHandler.java:51)
	at com.aerospike.jdbc.query.QueryPerformer.executeQuery(QueryPerformer.java:26)
	at com.aerospike.jdbc.AerospikeStatement.executeQuery(AerospikeStatement.java:52)
	at com.aerospike.jdbc.AerospikeStatement.execute(AerospikeStatement.java:141)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	... 10 more
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2022-10-19 19:23:26.865
!MESSAGE Error 20,1: Namespace not found in partition map: null
!STACK 0
com.aerospike.client.AerospikeException$InvalidNamespace: Error 20,1: Namespace not found in partition map: null
	at com.aerospike.client.query.PartitionTracker.assignPartitionsToNodes(PartitionTracker.java:194)
	at com.aerospike.client.command.ScanExecutor.scanPartitions(ScanExecutor.java:44)
	at com.aerospike.client.AerospikeClient.scanAll(AerospikeClient.java:2157)
	at com.aerospike.jdbc.schema.AerospikeSchemaBuilder.lambda$getSchema$4(AerospikeSchemaBuilder.java:48)
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at com.aerospike.jdbc.schema.AerospikeSchemaBuilder.getSchema(AerospikeSchemaBuilder.java:37)
	at com.aerospike.jdbc.query.SelectQueryHandler.execute(SelectQueryHandler.java:51)
	at com.aerospike.jdbc.query.QueryPerformer.executeQuery(QueryPerformer.java:26)
	at com.aerospike.jdbc.AerospikeStatement.executeQuery(AerospikeStatement.java:52)
	at com.aerospike.jdbc.AerospikeStatement.execute(AerospikeStatement.java:141)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:186)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4949)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by reugn** [comment]
Add the namespace name to the JDBC URL `jdbc:aerospike:{host}[:{port}]/dsclocal`.

**Comment by MohammadShabib** [comment]
it's working now only on DBeaver but still has the same issue on  JetBrains DataGrip.

can you add a feature where it will add the namespace name to the query automatically? because the database I use has over 50 namespaces, it is inconvenient to add them 1 by 1.

**Comment by reugn** [comment]
Fixed in [v1.7.1](https://github.com/aerospike/aerospike-jdbc/releases/tag/1.7.1).
